//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCourseWareProject.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Materials = new HashSet<Material>();
        }
    
        public int CId { get; set; }
        [Required, Display(Name = "Course Id")]
        public string CourseId { get; set; }
        [Required, Display(Name = "Course Title")]
        public string CourseTitle { get; set; }
        [Required, Display(Name = "Department")]
        public string Department { get; set; }
        [Required, Display(Name = "Instructor")]
        public string Instructor { get; set; }
        [Required, Display(Name = "Status")]
        public string Status { get; set; }
        [Required, Display(Name = "Added By")]
        public string AddedBy { get; set; }
        [Required, Display(Name = "Image Path")]
        public string ImagePath { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }

        public static IEnumerable<SelectListItem> GetStatusList()
        {
            IList<SelectListItem> status = new List<SelectListItem>
            {
                new SelectListItem() {Text="Active", Value="Active"},
                new SelectListItem() {Text="Archive", Value="Archive"}
            };
            return status;
        }
    }
}
